### ISSUE TITLE
Why codelab for this no longer available

### ISSUE THREAD

**Issue by Blasanka** [Janamou/firebase-counter#10]
I saw `This codelab is no longer available, but you can still look at the source code` and there isn't any courses about AngularDart in the https://codelabs.developers.google.com/

Why?

**Comment by kwalrath** [comment]
I'm glad you missed us!

We intend to publish updated AngularDart codelabs soon, but we couldn't do it in time for Google I/O, and we didn't want to feature old code during I/O.

As you might know, AngularDart is in the process of updating to Dart 2. This update involves a lot of moving pieces, including tools, which didn't support AngularDart with Dart 2 until very recently. (For example, JetBrains IDEs started supporting AngularDart with Dart 2 _today_.)

**Comment by Blasanka** [comment]
Sounds good. Thanks for the update.

**Comment by ptyagi911** [comment]
What's the update on Angular dart - firebase webapp code lab tutorial. I want to build my first webapp using dart and firebase, and not sure where to start :(
